

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gsbparautomobil;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author yanis
 */
public class ajoutVehicule extends javax.swing.JFrame {

    /**
     * Creates new form jFrameGSB2
     */
    JOptionPane jop1,jop2,jop3,jopok,jopnull;
public ajoutVehicule() {
        

initComponents();

//Importantion de la connection

Statement st2 =null;

    try{
            st2 = Connexion.getInstance().createStatement();
    }

    catch(SQLException e){
        e.printStackTrace();
    }


    try{

    ResultSet rs=st2.executeQuery("SELECT * FROM marque ");
    
    while(rs.next()){
        jMarque.addItem(rs.getString("libellé"));
    }
    
    rs.close();
    st2.close();
    }
    catch(Exception e)
    {
    e.printStackTrace();
    }
    }

/**
* This method is called from within the constructor to initialize the form.
* WARNING: Do NOT modify this code. The content of this method is always
* regenerated by the Form Editor.
*/
   
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jlabelModele = new javax.swing.JLabel();
        jLabelModele = new javax.swing.JLabel();
        jModele = new javax.swing.JTextField();
        jButtonValider = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jKm = new javax.swing.JTextField();
        jMarque = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        prix = new javax.swing.JTextField();
        jim = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setBackground(new java.awt.Color(153, 204, 255));
        jInternalFrame1.setTitle("Ajout d'un nouveau véhicule");
        jInternalFrame1.setVisible(true);

        jlabelModele.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jlabelModele.setForeground(new java.awt.Color(51, 51, 51));
        jlabelModele.setText("Marque");

        jLabelModele.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabelModele.setText("Modele");

        jModele.setText(" ");
        jModele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModeleActionPerformed(evt);
            }
        });

        jButtonValider.setText("Valider ");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel1.setText("KM");

        jMarque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMarqueActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel2.setText("Immatriculation");

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        jLabel3.setText("Prix");

        prix.setForeground(new java.awt.Color(255, 0, 0));
        prix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prixActionPerformed(evt);
            }
        });

        jim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimActionPerformed(evt);
            }
        });

        jButton1.setText("Effacer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("€");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButtonValider)
                        .addGap(93, 93, 93)
                        .addComponent(jButton1))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabelModele)
                                            .addComponent(jlabelModele))
                                        .addGap(64, 64, 64)
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jMarque, 0, 118, Short.MAX_VALUE)
                                            .addComponent(jModele)
                                            .addComponent(jim)
                                            .addComponent(prix)
                                            .addComponent(jKm)))
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(6, 6, 6)))))
                .addGap(0, 104, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMarque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelModele))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelModele)
                    .addComponent(jModele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(prix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(49, 49, 49)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValider)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed

        
        
Statement st2 =null;

    try{
    st2 = Connexion.getInstance().createStatement();}

    catch(SQLException e){
    e.printStackTrace();}     
       
    try
    {        
            
        String lib = jMarque.getSelectedItem().toString();
        System.out.print(lib);
        String query = "SELECT idMarque FROM marque WHERE libellé='"+lib+"' ";
        System.out.print(query);
        ResultSet rs1= st2.executeQuery(query);
        String id = null;
        
        if(jim.getText() == null && prix.getText() == null && jModele.getText() == null
                && jKm.getText() ==  null)
        {
            jopnull = new JOptionPane();
            jopnull.showMessageDialog(null,"Veuillez renseigner tout les champs × "); 
        }
        
    while(rs1.next())
    {   
        // nom=nomrs.GETSTRING(nom de la conlonne bdd)
        id= rs1.getString("idmarque"); 
        System.out.print(id);
    }
   
//      Requete qui insert l'id , le prix , 
    //  l'im,le modele , le km d'apres la valeurs rentrées

        String query2= "Insert INTO vehicule "
                + "(prix,Immatriculation,Modele,Kilometrage,idmarque,Disponibilite)"
                + "VALUES (?,?,?,?,'"+id+"',1) ";
   
// remplissage des trous avec les valeurs des boutons
   
        PreparedStatement prepare  = Connexion.getInstance().prepareStatement(query2);
        prepare.setString(1, prix.getText());
        prepare.setString(2, jim.getText());
        prepare.setString(3, jModele.getText());
        prepare.setString(4, jKm.getText());
   
//Execution de la requete

        prepare.executeUpdate();
        jopok = new JOptionPane();
        jopok.showMessageDialog(null,"Donnée complété, merci √ ");   
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    
    
   
    String px = prix.getText(); 
    int prix2 = Integer.parseInt(px);
    
    if(prix2>50000){
      prix.setCaretColor(Color.red);
        
      jop1= new JOptionPane();
      jop1.showMessageDialog(null,"attention aux prix"); 
    
      
    }
    
    
    }//GEN-LAST:event_jButtonValiderActionPerformed

    
    
    
    private void jModeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModeleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jModeleActionPerformed

    private void jMarqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMarqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMarqueActionPerformed

    private void prixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prixActionPerformed
        // TODO add your handling code here:
        /*
    JTextField field = new JTextField(); 
    JLabel jlabel= new JLabel("€");
    
    jlabel.setLabelFor(field);
    */

    }//GEN-LAST:event_prixActionPerformed

    private void jimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jimActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

     
jKm.setText("");
jim.setText("");
jModele.setText("");
prix.setText("");

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajoutVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajoutVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajoutVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajoutVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajoutVehicule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JTextField jKm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelModele;
    private javax.swing.JComboBox jMarque;
    private javax.swing.JTextField jModele;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jim;
    private javax.swing.JLabel jlabelModele;
    private javax.swing.JTextField prix;
    // End of variables declaration//GEN-END:variables
}
