/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gsbparautomobil;

/**
 *
 * @author todob_000
 */
public class MenuAppli extends javax.swing.JFrame {

    /**
     * Creates new form MenuAppli
     */
    public MenuAppli() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuAttribution = new javax.swing.JMenu();
        jMIAtt = new javax.swing.JMenuItem();
        jMenuAjout = new javax.swing.JMenu();
        jMIAj = new javax.swing.JMenuItem();
        jMenuRetours = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("GSB APPLICATION");
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 140));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuAttribution.setText("AttributionVéhicule");

        jMIAtt.setText("Attribution d'un véhicule");
        jMIAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAttActionPerformed(evt);
            }
        });
        jMenuAttribution.add(jMIAtt);

        jMenuBar1.add(jMenuAttribution);

        jMenuAjout.setText("ajoutVéhicule");

        jMIAj.setText("Ajout d'un véhicule");
        jMIAj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAjActionPerformed(evt);
            }
        });
        jMenuAjout.add(jMIAj);

        jMenuBar1.add(jMenuAjout);

        jMenuRetours.setText("RetoursVéhicule");
        jMenuRetours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRetoursActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuRetours);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAttActionPerformed
        // TODO add your handling code here:
        AttributionVehicule fen1 = new AttributionVehicule();
        fen1.setVisible(true);
    }//GEN-LAST:event_jMIAttActionPerformed

    private void jMIAjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAjActionPerformed
        // TODO add your handling code here:
        ajoutVehicule fen2 = new ajoutVehicule();
        fen2.setVisible(true);
    }//GEN-LAST:event_jMIAjActionPerformed

    private void jMenuRetoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRetoursActionPerformed
        RetourVehicule fen3 = new RetourVehicule();
        fen3.setVisible(true);
    }//GEN-LAST:event_jMenuRetoursActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAppli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAppli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAppli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAppli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAppli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMIAj;
    private javax.swing.JMenuItem jMIAtt;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuAjout;
    private javax.swing.JMenu jMenuAttribution;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuRetours;
    // End of variables declaration//GEN-END:variables
}
